[project]
name = "ticket-support"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[all]>=0.116.1",
    "openai>=1.101.0",
    "pandas>=2.3.2",
    "scikit-learn>=1.7.1",
]
